# Generated by Django 4.0.3 on 2022-03-18 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='dest path', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'mpeg'])])),
                ('original_size', models.IntegerField(blank=True, null=True, verbose_name='video size in kilobytes')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='duration')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_date', 'duration'),
            },
        ),
    ]
